const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_10_54_10_19_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAyMjgsXG4gICAgICAgIDE5NyxcbiAgICAgICAgOTUsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjI2LFxuICAgICAgICA5NixcbiAgICAgICAgNyxcbiAgICAgICAgMTY0LFxuICAgICAgICAyMzUsXG4gICAgICAgIDI0MixcbiAgICAgICAgOTMsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMzMsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE3LFxuICAgICAgICA5MSxcbiAgICAgICAgMTA1LFxuICAgICAgICA4OCxcbiAgICAgICAgMTMsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTQwLFxuICAgICAgICAyMzYsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTc5LFxuICAgICAgICAxOCxcbiAgICAgICAgMTU1LFxuICAgICAgICA4NSxcbiAgICAgICAgMTkyLFxuICAgICAgICA3MSxcbiAgICAgICAgMTAyXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyMyxcbiAgICAgICAgNjIsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTEwLFxuICAgICAgICA0NixcbiAgICAgICAgMjUsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTQ3LFxuICAgICAgICA1MyxcbiAgICAgICAgMTEwLFxuICAgICAgICA3NyxcbiAgICAgICAgMTM3LFxuICAgICAgICAxMzAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjksXG4gICAgICAgIDc0LFxuICAgICAgICAxNSxcbiAgICAgICAgMTAxLFxuICAgICAgICAyNDgsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNjksXG4gICAgICAgIDQsXG4gICAgICAgIDE1NixcbiAgICAgICAgNzcsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTMzLFxuICAgICAgICAyNixcbiAgICAgICAgNzMsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTMzLFxuICAgICAgICA5NCxcbiAgICAgICAgNjJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExMixcbiAgICAgICAgMTAyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAxNzgsXG4gICAgICAgIDc3LFxuICAgICAgICA5LFxuICAgICAgICA4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTUsXG4gICAgICAgIDIxMCxcbiAgICAgICAgOSxcbiAgICAgICAgNTMsXG4gICAgICAgIDU4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE3NCxcbiAgICAgICAgNjgsXG4gICAgICAgIDE4NCxcbiAgICAgICAgODEsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNTEsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTQ1LFxuICAgICAgICA1MCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTczLFxuICAgICAgICAyMzAsXG4gICAgICAgIDEwNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxOTgsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTM3LFxuICAgICAgICAxNjcsXG4gICAgICAgIDExNyxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMjksXG4gICAgICAgIDAsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTc1LFxuICAgICAgICAxNjcsXG4gICAgICAgIDM0LFxuICAgICAgICA0NixcbiAgICAgICAgMTUyLFxuICAgICAgICAyNDEsXG4gICAgICAgIDU2LFxuICAgICAgICAyMTIsXG4gICAgICAgIDYwLFxuICAgICAgICAxMjEsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTcsXG4gICAgICAgIDQsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjcsXG4gICAgICAgIDM3LFxuICAgICAgICAyMTUsXG4gICAgICAgIDE5MixcbiAgICAgICAgMTYsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDEzMixcbiAgICAgICAgNDEsXG4gICAgICAgIDc1LFxuICAgICAgICAxODksXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjI0LFxuICAgICAgICAxNDEsXG4gICAgICAgIDY1LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNDUsXG4gICAgICAgIDE1NSxcbiAgICAgICAgODcsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTYyLFxuICAgICAgICA3MyxcbiAgICAgICAgMTU4LFxuICAgICAgICAxNTksXG4gICAgICAgIDIxOCxcbiAgICAgICAgNjcsXG4gICAgICAgIDI1LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTYwLFxuICAgICAgICAxNTUsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTg4LFxuICAgICAgICA5NCxcbiAgICAgICAgOTZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA5LFxuICAgICAgICAyNTUsXG4gICAgICAgIDEyMixcbiAgICAgICAgODAsXG4gICAgICAgIDE1LFxuICAgICAgICA2NCxcbiAgICAgICAgMjIwLFxuICAgICAgICAyNTAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNTQsXG4gICAgICAgIDEwMixcbiAgICAgICAgMjEyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDYwLFxuICAgICAgICAxMzQsXG4gICAgICAgIDU5LFxuICAgICAgICAxMTMsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTcsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNTUsXG4gICAgICAgIDE3NixcbiAgICAgICAgMzMsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTU5LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTAwLFxuICAgICAgICA3MyxcbiAgICAgICAgODUsXG4gICAgICAgIDczLFxuICAgICAgICAyNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDE2NCxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICA5MFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA4LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDExMixcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxMTBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0NCxcbiAgICAgICAgMTE5LFxuICAgICAgICAyMSxcbiAgICAgICAgNyxcbiAgICAgICAgMTIxLFxuICAgICAgICAyNTQsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNjgsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjA5LFxuICAgICAgICAxODAsXG4gICAgICAgIDk3LFxuICAgICAgICA0OSxcbiAgICAgICAgMTIyLFxuICAgICAgICAyMDQsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTk4LFxuICAgICAgICAxMDgsXG4gICAgICAgIDgyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDg0LFxuICAgICAgICAyNDcsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTQzLFxuICAgICAgICA3NCxcbiAgICAgICAgMjA1LFxuICAgICAgICA1OSxcbiAgICAgICAgMjI1LFxuICAgICAgICA5LFxuICAgICAgICAyMzEsXG4gICAgICAgIDIyLFxuICAgICAgICAxOTksXG4gICAgICAgIDEwMSxcbiAgICAgICAgNzUsXG4gICAgICAgIDk4LFxuICAgICAgICA2OCxcbiAgICAgICAgMTgsXG4gICAgICAgIDU0LFxuICAgICAgICA5OSxcbiAgICAgICAgMTkxLFxuICAgICAgICAxMSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNjcsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTM3LFxuICAgICAgICA1MyxcbiAgICAgICAgMzcsXG4gICAgICAgIDI1LFxuICAgICAgICAzMyxcbiAgICAgICAgMTUsXG4gICAgICAgIDIsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTAzLFxuICAgICAgICAxNDAsXG4gICAgICAgIDk4LFxuICAgICAgICA1LFxuICAgICAgICAxMDcsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMjhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEzNyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJoai96ek9kV0RoVVpvMmZuNGlxZk9QQ3pvMGkwYytWKzMxSVN2QW9UWW00PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJ4bFd0eG11V1JQS0lUS04zc2lrVWRBXCIsXG4gIFwicGhvbmVJZFwiOiBcIjRhNTE0NjdlLTk3YjYtNGQ2OC04NmNjLThmNTFhYWRlMTQwYlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzAsXG4gICAgICA2OSxcbiAgICAgIDE3NCxcbiAgICAgIDcyLFxuICAgICAgOTEsXG4gICAgICAxMTMsXG4gICAgICAxNzksXG4gICAgICAxNjAsXG4gICAgICAxNzcsXG4gICAgICAxNDQsXG4gICAgICA2OCxcbiAgICAgIDcwLFxuICAgICAgODIsXG4gICAgICAzNixcbiAgICAgIDEyNyxcbiAgICAgIDEwMCxcbiAgICAgIDIxNCxcbiAgICAgIDE3NSxcbiAgICAgIDg5LFxuICAgICAgMTM5XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEyOSxcbiAgICAgIDQzLFxuICAgICAgMTM3LFxuICAgICAgMTU4LFxuICAgICAgMjM0LFxuICAgICAgMTgzLFxuICAgICAgMjAsXG4gICAgICAyMSxcbiAgICAgIDE0MSxcbiAgICAgIDgzLFxuICAgICAgMTg3LFxuICAgICAgNzgsXG4gICAgICAxMDcsXG4gICAgICAyMzAsXG4gICAgICA2NyxcbiAgICAgIDE3OSxcbiAgICAgIDIyLFxuICAgICAgNjYsXG4gICAgICAxMDIsXG4gICAgICAxNzhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiNkdOVEZWQ1hcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1NDc2OTk2NzY2OToyMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTQwNjUxNTg5MDI1ODQ0OjIxQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ01LVHViNERFTlNmenJnR0dBb2dBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiUlNJcE5lYmorNWFjWmt6OUhhN2hDSGRzNFVVZHNHSExWNHVOM2UrMEp6UT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJVcjVQVmNkVHJYcEYxN0xnWUZUNFpzY05RMFNpOXFEeVg5Q3RDR0ZmUVBqUjBSbHkyTno0WjRYT2NDc25OMU9NSFRIUnIzK28zazU5WjRxeTFhRVJEQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJjSFlSbXAya0h1VFcvSWYvanR4NmFmRmRSZVJNUXRFVW8wM1JTWG9DQWw4YTFZUjI0NXNMQUdiKzFORG5HRmRZdGRaQ2lTaDdydGRxQk9rU2M2cGtoZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNTQ3Njk5Njc2Njk6MjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICA1MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI5MzM1MjU3LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSEtxXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFIS3EuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJMbkhzNExDRHBtTXg5ZlZVVXY0TVRJSHp5SXVrd0dmZ09TOTZ1QWRkczhjPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjkzNjI2NjE3OCxcImN1cnJlbnRJbmRleFwiOjksXCJkZXZpY2VJbmRleGVzXCI6WzAsMyw5XX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjkzMzUxOTk4NzRcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
